echo  [START] Launching Vue frontend on http://localhost:5173 ...
cd frontend && npm run dev &

echo  [START] Launching FastAPI backend on http://localhost:8000 ...
cd backend && python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000

